/*
 * Package with at least one class required for Javac to compile classes generated by Japid
 * from html templates. They import this package (contain "import japidviews._javatags.*" line).
 * Javac cannot be configured to ignore this case (JDT compiler embedded in Play! is configured
 * to ignore it).
 */
package japidviews._javatags;

public class dummy
{
}